idf_component_register(
    SRCS 
        "main.cpp"
        "telemetry_task.cpp"
        "transport_uart.cpp"
        "transport_wifi_udp.cpp"
        "gnc_task.cpp"
        "fdir_manager.cpp"
        "timer_watchdog.cpp"
    INCLUDE_DIRS 
        "."
        "../include"
    REQUIRES 
        freertos 
        driver 
        esp_driver_i2c 
        esp_driver_gptimer 
        esp_hw_support 
        esp_timer 
        nvs_flash 
        esp_wifi 
        esp_netif 
        esp_event 
        lwip 
        matrix 
        ekf 
        mpu6050
)
